version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
  doc:
    build:
      context: ../../
      dockerfile: ./docker/godoc/Dockerfile
    ports:
      - 6060:6060
  api:
    build:
      context: ../../
      dockerfile: ./docker/golang/Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DATABASE_URL: db
    depends_on:
      - db
      - doc
