version: '3.3'

services:
  doc:
    build:
      context: ../../
      dockerfile: ./docker/godoc/Dockerfile
    ports:
      - 6060:6060
  api:
    build:
      context: ../../
      dockerfile: ./docker/golang/Dockerfile
    ports:
      - 8090:8090
    environment:
      PORT: 8090
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: klv
