version: '3.3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DATABASE_URL: db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
