version: '3.1'

services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    networks:
      - fullstack

  app:
    build: .
    container_name: app
    environment:
      - DB_USER: ${DATABASE_PASSWORD}
      - DB_PASS: ${DATABASE_NAME}
      - DB_NAME: ${DATABASE_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
